# app/ui/gradio_app.py
#
# Gradio UI for the Tech Explanation Service.
# This module defines an interactive web interface that allows users
# to input a technical topic and receive an AI-generated explanation.
# The UI delegates all business logic to the TechExplanationService.

import gradio as gr

from app.services.tech_explanation_service import TechExplanationService


# ------------------------------------------------------------------
# Service initialization
# ------------------------------------------------------------------
# The service wraps the LCEL chain and exposes a simple application API.
service = TechExplanationService()


# ------------------------------------------------------------------
# Streaming callback 
# ------------------------------------------------------------------
def explain_topic_stream(topic: str):
    # Stream explanation chunk by chunk using LCEL's .stream().
    if not topic or not topic.strip():
        yield "Please enter a technical topic."
        return

    # LCEL chain returns a generator of partial outputs
    for chunk in service.tech_chain_stream(topic.strip()):
        yield chunk


# ------------------------------------------------------------------
# UI callback
# ------------------------------------------------------------------
def explain_topic(topic: str) -> str:
    
    # --- Gradio callback function. ---
    #
    # Args:
    #     topic (str): The technical topic provided by the user.
    #
    # Returns:
    #     str: The generated explanation.

    if not topic or not topic.strip():
        return "Please enter a technical topic."

    return service.explain(topic.strip())


# ------------------------------------------------------------------
# Gradio interface definition
# ------------------------------------------------------------------
# app/ui/gradio_app.py
#
# Gradio UI for the Tech Explanation Service.
# This module defines an interactive web interface that allows users
# to input a technical topic and receive an AI-generated explanation.
# The UI delegates all business logic to the TechExplanationService.

import gradio as gr
from app.services.tech_explanation_service import TechExplanationService


# ------------------------------------------------------------------
# Service initialization
# ------------------------------------------------------------------
# The service wraps the LCEL chain and exposes a simple application API.
service = TechExplanationService()


# ------------------------------------------------------------------
# UI callback
# ------------------------------------------------------------------
def explain_topic_stream(topic: str) -> str:
    
    # --- Gradio callback function. ---
    #
    # Args:
    #     topic (str): The technical topic provided by the user.
    #
    # Yields:
    #     str: The generated explanation.

    if not topic or not topic.strip():
        yield "Please enter a technical topic."
        return

    # LCEL chain returns a generator of partial outputs
    for chunk in service.tech_chain_stream(topic.strip()):
        yield chunk
    

# ------------------------------------------------------------------
# Gradio interface definition
# ------------------------------------------------------------------
with gr.Blocks(title="Tech Explanation Service") as demo:
    gr.Markdown(
        """
        # Tech Explanation Service

        Enter a technical topic and receive a clear, structured explanation
        generated by an AI model.

        This demo showcases a **LangChain LCEL-based architecture** with a
        clean separation between UI, service layer, and LLM logic.
        """
    )

    with gr.Column():
        topic_input = gr.Textbox(
            label="Technical Topic",
            placeholder="e.g. Transformer architecture in NLP",
            lines=1,
        )

        explain_button = gr.Button(
            "Explain",
            size="sm",
        )

        output = gr.Markdown(label="Explanation")

    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------
    # Trigger explanation on button click
    explain_button.click(
        fn=explain_topic_stream,
        inputs=topic_input,
        outputs=output,
    )

    # Trigger explanation when pressing Enter in the textbox
    topic_input.submit(
        fn=explain_topic_stream,
        inputs=topic_input,
        outputs=output,
    )


    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------
    # Trigger explanation on button click
    explain_button.click(
        fn=explain_topic,
        inputs=topic_input,
        outputs=output,
    )

    # Trigger explanation when pressing Enter in the textbox
    topic_input.submit(
        fn=explain_topic,
        inputs=topic_input,
        outputs=output,
    )
